# ---------- default: LOCAL ----------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_nest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root           # <-- your local DB user
    password: 123456789      # <-- your local DB password
  jpa:
    hibernate:
      ddl-auto: update       # dev only; use migrations later
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080


# ---------- ISAAC DB PROFILE ----------
---
spring:
  config:
    activate:
      on-profile: isaac

  datasource:
    url: jdbc:mysql://puggu.dev:3306/student_nest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${STUDENT_NEST_DB_USERNAME}
    password: ${STUDENT_NEST_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
